name: Android CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'fastlane/**'
      - '.github/**'
      - '!.github/workflows/android.yml'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'fastlane/**'
      - '.github/**'
      - '!.github/workflows/android.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, '[skip ci]') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build with Gradle
        run: |
          echo "commit=$(echo ${{ github.sha }} | cut -c-7)" >> $GITHUB_ENV
          ./gradlew assembleDebug
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Hail@${{ env.commit }}
          path: app/build/outputs/apk/debug/*.apk
